/* =============================================================
   APHELION — Interactive 3D Solar System
   Three.js r160 · ES Modules · Procedurally textured (no external
   image assets — every texture below is painted at runtime onto
   an offscreen <canvas>, so the simulator works fully offline).
   ============================================================= */

import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import { Lensflare, LensflareElement } from 'three/addons/objects/Lensflare.js';

/* ---------------------------------------------------------------
   0. GLOBAL CONFIG
   --------------------------------------------------------------- */
const IS_MOBILE = window.innerWidth < 768 || /Mobi|Android/i.test(navigator.userAgent);
const DPR = Math.min(window.devicePixelRatio || 1, IS_MOBILE ? 2 : 2.5);

const QUALITY = {
  starCount: IS_MOBILE ? 3500 : 9000,
  asteroidCount: IS_MOBILE ? 450 : 1400,
  bloom: true,
  shadows: !IS_MOBILE,
  textureSize: IS_MOBILE ? 512 : 1024,
};

const YEAR_SECONDS = 24;     // seconds for Earth to complete one orbit at 1x speed
const AU = 1;                // (unused directly — distances already scaled below)

const state = {
  playing: true,
  speed: 1,
  showOrbits: true,
  showLabels: true,
  simDays: 0,
  selected: null,
  flight: null,             // active camera transition
};

/* ---------------------------------------------------------------
   1. LOADER HELPERS
   --------------------------------------------------------------- */
const loaderEl = document.getElementById('loader');
const loaderBar = document.getElementById('loader-progress');
const loaderStatus = document.getElementById('loader-status');
function setLoad(pct, msg){
  loaderBar.style.width = pct + '%';
  if (msg) loaderStatus.textContent = msg;
}
function nextFrame(){ return new Promise(r => requestAnimationFrame(r)); }

/* ---------------------------------------------------------------
   2. PLANET DATA
   --------------------------------------------------------------- */
const PLANETS = [
  {
    key:'mercury', name:'Mercury', type:'TERRESTRIAL PLANET',
    radius:0.62, distance:19, orbitPeriodDays:88, rotationPeriodDays:58.6, rotationDir:1,
    tilt:0.001, texture:'rocky',
    palette:['#8c8378','#6e6560','#a89f8f','#4f473f'],
    desc:'A cratered, sun-blasted world with almost no atmosphere and the widest temperature swing of any planet.',
    facts:{
      diameter:'4,879 km', distance:'57.9 million km', moons:'0',
      day:'59 Earth days', year:'88 Earth days', temp:'167°C day / −173°C night'
    },
    notes:[
      'Closest planet to the Sun, yet not the hottest — that title belongs to Venus.',
      'A day on Mercury (sunrise to sunrise) lasts longer than its entire year.',
      'Its surface closely resembles the Moon, scarred by billions of years of impacts.'
    ]
  },
  {
    key:'venus', name:'Venus', type:'TERRESTRIAL PLANET',
    radius:1.05, distance:26, orbitPeriodDays:225, rotationPeriodDays:243, rotationDir:-1,
    tilt:0.045, texture:'venus',
    palette:['#e8c789','#d9a856','#f0d9a0','#c99a52'],
    desc:'Earth\u2019s hellish twin, wrapped in a crushing carbon-dioxide atmosphere and clouds of sulfuric acid.',
    facts:{
      diameter:'12,104 km', distance:'108.2 million km', moons:'0',
      day:'243 Earth days', year:'225 Earth days', temp:'464°C'
    },
    notes:[
      'Venus spins backwards — the Sun rises in the west and sets in the east.',
      'Surface pressure is roughly 92 times that of Earth, like being 900 m underwater.',
      'It is the hottest planet in the solar system, hotter even than Mercury.'
    ]
  },
  {
    key:'earth', name:'Earth', type:'TERRESTRIAL PLANET',
    radius:1.1, distance:34, orbitPeriodDays:365.25, rotationPeriodDays:1, rotationDir:1,
    tilt:0.41, texture:'earth',
    palette:['#2a5ea8','#1c3f73','#3d7a3d','#8a6a42'],
    desc:'The only known world with liquid oceans, plate tectonics, and life — our home.',
    facts:{
      diameter:'12,742 km', distance:'149.6 million km', moons:'1',
      day:'24 hours', year:'365.25 days', temp:'15°C average'
    },
    notes:[
      'About 71% of Earth\u2019s surface is covered by water.',
      'Its magnetic field, generated by a molten iron core, shields us from solar wind.',
      'The Moon stabilizes Earth\u2019s axial tilt, keeping our seasons predictable.'
    ],
    moons:[{ name:'Moon', radius:0.3, distance:2.4, orbitPeriodDays:27.3, rotationPeriodDays:27.3, palette:['#b8b3ab','#8f897f'] }]
  },
  {
    key:'mars', name:'Mars', type:'TERRESTRIAL PLANET',
    radius:0.72, distance:42, orbitPeriodDays:687, rotationPeriodDays:1.03, rotationDir:1,
    tilt:0.44, texture:'mars',
    palette:['#b1502f','#8a3a22','#c96a41','#6e2f1c'],
    desc:'The Red Planet — a cold desert world with the largest volcano and canyon in the solar system.',
    facts:{
      diameter:'6,779 km', distance:'227.9 million km', moons:'2',
      day:'24h 37m', year:'687 Earth days', temp:'−65°C average'
    },
    notes:[
      'Home to Olympus Mons, a volcano nearly three times the height of Mount Everest.',
      'Its rust-red color comes from iron oxide covering the surface.',
      'Its two tiny moons, Phobos and Deimos, are likely captured asteroids.'
    ]
  },
  {
    key:'jupiter', name:'Jupiter', type:'GAS GIANT',
    radius:4.6, distance:64, orbitPeriodDays:4333, rotationPeriodDays:0.41, rotationDir:1,
    tilt:0.055, texture:'jupiter',
    palette:['#d8c39a','#b98f5e','#e8dcc3','#9c6a42','#c77a4a'],
    desc:'The largest planet in the solar system, a churning giant of hydrogen and helium with a storm bigger than Earth.',
    facts:{
      diameter:'139,820 km', distance:'778.5 million km', moons:'95',
      day:'9h 56m', year:'11.9 Earth years', temp:'−110°C average'
    },
    notes:[
      'The Great Red Spot is a storm larger than Earth that has raged for centuries.',
      'Jupiter has the shortest day of any planet despite its immense size.',
      'It acts as a gravitational shield, deflecting comets and asteroids away from Earth.'
    ]
  },
  {
    key:'saturn', name:'Saturn', type:'GAS GIANT',
    radius:3.9, distance:82, orbitPeriodDays:10759, rotationPeriodDays:0.45, rotationDir:1,
    tilt:0.47, texture:'saturn', hasRings:true,
    palette:['#e6d5a8','#cbb583','#f2e6c2','#b89d6b'],
    desc:'Famed for its dazzling ring system made of billions of ice and rock particles.',
    facts:{
      diameter:'116,460 km', distance:'1.43 billion km', moons:'146',
      day:'10h 42m', year:'29.5 Earth years', temp:'−140°C average'
    },
    notes:[
      'Saturn is the least dense planet — it would float in a bathtub large enough to hold it.',
      'Its rings span up to 280,000 km across but are often less than 1 km thick.',
      'Titan, its largest moon, has thick clouds and lakes of liquid methane.'
    ]
  },
  {
    key:'uranus', name:'Uranus', type:'ICE GIANT',
    radius:2.4, distance:100, orbitPeriodDays:30687, rotationPeriodDays:0.72, rotationDir:-1,
    tilt:1.71, texture:'uranus',
    palette:['#bfe9e6','#9bd4d0','#d6f2ef','#7fc3bf'],
    desc:'A pale, tilted ice giant that essentially rolls around the Sun on its side.',
    facts:{
      diameter:'50,724 km', distance:'2.87 billion km', moons:'28',
      day:'17h 14m', year:'84 Earth years', temp:'−195°C average'
    },
    notes:[
      'Its axis is tilted roughly 98°, so it spins almost like a rolling ball.',
      'Uranus has faint rings, discovered in 1977 through stellar occultation.',
      'Its blue-green color comes from methane absorbing red light in the atmosphere.'
    ]
  },
  {
    key:'neptune', name:'Neptune', type:'ICE GIANT',
    radius:2.3, distance:116, orbitPeriodDays:60190, rotationPeriodDays:0.67, rotationDir:1,
    tilt:0.49, texture:'neptune',
    palette:['#3454c9','#233c99','#4d6de0','#1b2c73'],
    desc:'The windiest planet, a deep blue ice giant at the outer edge of the known solar system.',
    facts:{
      diameter:'49,244 km', distance:'4.50 billion km', moons:'16',
      day:'16h 6m', year:'165 Earth years', temp:'−200°C average'
    },
    notes:[
      'Neptune has the fastest winds in the solar system, reaching over 2,000 km/h.',
      'It was the first planet located by mathematical prediction rather than direct observation.',
      'One Neptunian year takes about 165 Earth years to complete.'
    ]
  }
];

const SUN = { radius: 11, name:'Sun' };
const BELT_INNER = 49, BELT_OUTER = 59;

/* ---------------------------------------------------------------
   3. RENDERER / SCENE / CAMERA
   --------------------------------------------------------------- */
const root = document.getElementById('scene-root');
const scene = new THREE.Scene();

const camera = new THREE.PerspectiveCamera(45, window.innerWidth/window.innerHeight, 0.1, 6000);
const DEFAULT_CAM_POS = new THREE.Vector3(0, 55, 150);
const DEFAULT_TARGET = new THREE.Vector3(0,0,0);
camera.position.copy(DEFAULT_CAM_POS);

const renderer = new THREE.WebGLRenderer({ antialias: !IS_MOBILE, powerPreference:'high-performance', logarithmicDepthBuffer:true });
renderer.setPixelRatio(DPR);
renderer.setSize(window.innerWidth, window.innerHeight);
renderer.outputColorSpace = THREE.SRGBColorSpace;
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure = 1.15;
if (QUALITY.shadows){
  renderer.shadowMap.enabled = true;
  renderer.shadowMap.type = THREE.PCFSoftShadowMap;
}
root.appendChild(renderer.domElement);

const controls = new OrbitControls(camera, renderer.domElement);
controls.enableDamping = true;
controls.dampingFactor = 0.06;
controls.minDistance = 4;
controls.maxDistance = 900;
controls.target.copy(DEFAULT_TARGET);

/* Post-processing */
const composer = new EffectComposer(renderer);
composer.addPass(new RenderPass(scene, camera));
let bloomPass = null;
if (QUALITY.bloom){
  bloomPass = new UnrealBloomPass(new THREE.Vector2(window.innerWidth, window.innerHeight), 0.85, 0.55, 0.15);
  composer.addPass(bloomPass);
}
composer.addPass(new OutputPass());

/* ---------------------------------------------------------------
   4. PROCEDURAL TEXTURE GENERATORS
   --------------------------------------------------------------- */
const TS = QUALITY.textureSize;

function makeCanvas(w = TS, h = TS/2){
  const c = document.createElement('canvas');
  c.width = w; c.height = h;
  return { c, ctx: c.getContext('2d') };
}
function rand(min,max){ return Math.random()*(max-min)+min; }
function pick(arr){ return arr[(Math.random()*arr.length)|0]; }

function toTexture(canvas, colorData = true){
  const tex = new THREE.CanvasTexture(canvas);
  tex.wrapS = THREE.RepeatWrapping;
  tex.anisotropy = 4;
  if (colorData) tex.colorSpace = THREE.SRGBColorSpace;
  tex.needsUpdate = true;
  return tex;
}

/* Mottled rocky/cratered surface (Mercury, Mars) */
function textureRocky(palette){
  const { c, ctx } = makeCanvas();
  ctx.fillStyle = palette[0]; ctx.fillRect(0,0,c.width,c.height);
  for (let i=0;i<420;i++){
    ctx.globalAlpha = rand(0.08,0.32);
    ctx.fillStyle = pick(palette);
    const x = rand(0,c.width), y = rand(0,c.height), r = rand(4, c.width*0.05);
    ctx.beginPath(); ctx.ellipse(x,y,r,r*rand(0.6,1),rand(0,Math.PI),0,Math.PI*2); ctx.fill();
  }
  ctx.globalAlpha = 1;
  // craters
  for (let i=0;i<160;i++){
    const x = rand(0,c.width), y = rand(0,c.height), r = rand(3,22);
    const grad = ctx.createRadialGradient(x,y,0,x,y,r);
    grad.addColorStop(0,'rgba(0,0,0,0.35)');
    grad.addColorStop(0.7,'rgba(0,0,0,0.12)');
    grad.addColorStop(1,'rgba(0,0,0,0)');
    ctx.fillStyle = grad;
    ctx.beginPath(); ctx.arc(x,y,r,0,Math.PI*2); ctx.fill();
    ctx.strokeStyle = 'rgba(255,255,255,0.06)';
    ctx.beginPath(); ctx.arc(x,y,r*1.05,0,Math.PI*2); ctx.stroke();
  }
  return toTexture(c);
}

/* Thick swirling cloud world (Venus) */
function textureVenus(palette){
  const { c, ctx } = makeCanvas();
  const grad = ctx.createLinearGradient(0,0,0,c.height);
  grad.addColorStop(0, palette[2]); grad.addColorStop(1, palette[1]);
  ctx.fillStyle = grad; ctx.fillRect(0,0,c.width,c.height);
  for (let i=0;i<60;i++){
    const y = rand(0,c.height);
    ctx.strokeStyle = pick(palette);
    ctx.globalAlpha = rand(0.06,0.18);
    ctx.lineWidth = rand(4,18);
    ctx.beginPath();
    ctx.moveTo(0, y);
    for (let x=0;x<=c.width;x+=40){
      ctx.lineTo(x, y + Math.sin(x*0.02+i)*14);
    }
    ctx.stroke();
  }
  ctx.globalAlpha = 1;
  return toTexture(c);
}

/* Banded gas / ice giant with optional storm spot */
function textureBanded(palette, { storm=false, turbulence=1 } = {}){
  const { c, ctx } = makeCanvas();
  const bandCount = 18;
  let y = 0;
  const bandH = c.height / bandCount;
  for (let i=0;i<bandCount;i++){
    ctx.fillStyle = pick(palette);
    ctx.fillRect(0, y, c.width, bandH+1);
    y += bandH;
  }
  // horizontal turbulence via sine-warped overlay strips
  for (let i=0;i<70*turbulence;i++){
    const yy = rand(0,c.height);
    ctx.strokeStyle = pick(palette);
    ctx.globalAlpha = rand(0.05,0.16);
    ctx.lineWidth = rand(2,10);
    ctx.beginPath();
    ctx.moveTo(0,yy);
    for (let x=0;x<=c.width;x+=30){
      ctx.lineTo(x, yy + Math.sin(x*0.03+i*3)*10*turbulence);
    }
    ctx.stroke();
  }
  ctx.globalAlpha = 1;
  if (storm){
    const sx = c.width*0.32, sy = c.height*0.62, sr = c.width*0.09;
    const grad = ctx.createRadialGradient(sx,sy,sr*0.1,sx,sy,sr);
    grad.addColorStop(0,'#e2694a'); grad.addColorStop(0.6,'#c85436'); grad.addColorStop(1,'rgba(200,84,54,0)');
    ctx.fillStyle = grad;
    ctx.beginPath(); ctx.ellipse(sx,sy,sr,sr*0.62,0,0,Math.PI*2); ctx.fill();
  }
  return toTexture(c);
}

/* Earth: oceans + continents + polar caps */
function textureEarth(palette){
  const { c, ctx } = makeCanvas();
  ctx.fillStyle = palette[0]; ctx.fillRect(0,0,c.width,c.height);
  // continents
  for (let i=0;i<26;i++){
    ctx.fillStyle = Math.random()>0.3 ? palette[2] : palette[3];
    ctx.globalAlpha = rand(0.55,0.9);
    const cx = rand(0,c.width), cy = rand(c.height*0.12,c.height*0.88);
    ctx.beginPath();
    const pts = 8;
    for (let p=0;p<=pts;p++){
      const a = (p/pts)*Math.PI*2;
      const r = rand(c.width*0.02, c.width*0.075);
      const x = cx + Math.cos(a)*r, y = cy + Math.sin(a)*r*0.7;
      p===0 ? ctx.moveTo(x,y) : ctx.lineTo(x,y);
    }
    ctx.closePath(); ctx.fill();
  }
  ctx.globalAlpha = 1;
  // polar caps
  const capH = c.height*0.09;
  let g1 = ctx.createLinearGradient(0,0,0,capH*1.6);
  g1.addColorStop(0,'rgba(255,255,255,0.95)'); g1.addColorStop(1,'rgba(255,255,255,0)');
  ctx.fillStyle = g1; ctx.fillRect(0,0,c.width,capH*1.6);
  let g2 = ctx.createLinearGradient(0,c.height,0,c.height-capH*1.6);
  g2.addColorStop(0,'rgba(255,255,255,0.95)'); g2.addColorStop(1,'rgba(255,255,255,0)');
  ctx.fillStyle = g2; ctx.fillRect(0,c.height-capH*1.6,c.width,capH*1.6);
  return toTexture(c);
}

/* Cloud layer (transparent, additive white wisps) for Earth */
function textureClouds(){
  const { c, ctx } = makeCanvas();
  ctx.clearRect(0,0,c.width,c.height);
  for (let i=0;i<70;i++){
    ctx.globalAlpha = rand(0.08,0.22);
    ctx.fillStyle = '#ffffff';
    const x = rand(0,c.width), y = rand(0,c.height);
    const r = rand(10, c.width*0.05);
    ctx.beginPath(); ctx.ellipse(x,y,r,r*0.4,rand(0,Math.PI),0,Math.PI*2); ctx.fill();
  }
  const tex = new THREE.CanvasTexture(c);
  tex.wrapS = THREE.RepeatWrapping;
  return tex;
}

/* Saturn-style ring (radial alpha bands) */
function textureRing(baseColor){
  const w = 512, h = 64;
  const c = document.createElement('canvas'); c.width=w; c.height=h;
  const ctx = c.getContext('2d');
  for (let x=0;x<w;x++){
    const t = x/w;
    const noise = Math.sin(t*80)*0.5+0.5;
    const alpha = (0.15 + 0.55*noise*Math.sin(t*13+1.3)*Math.sin(t*13+1.3)) * (t>0.03 && t<0.97 ? 1: 0);
    ctx.fillStyle = baseColor;
    ctx.globalAlpha = Math.max(0, Math.min(1,alpha));
    ctx.fillRect(x,0,1,h);
  }
  const tex = new THREE.CanvasTexture(c);
  tex.colorSpace = THREE.SRGBColorSpace;
  tex.needsUpdate = true;
  return tex;
}

/* Sun surface */
function textureSun(){
  const { c, ctx } = makeCanvas();
  const grad = ctx.createRadialGradient(c.width/2,c.height/2,0,c.width/2,c.height/2,c.width/2);
  grad.addColorStop(0,'#fff6d6'); grad.addColorStop(0.4,'#ffd27a'); grad.addColorStop(0.75,'#ffab4a'); grad.addColorStop(1,'#ff8a3d');
  ctx.fillStyle = grad; ctx.fillRect(0,0,c.width,c.height);
  for (let i=0;i<260;i++){
    ctx.globalAlpha = rand(0.05,0.18);
    ctx.fillStyle = Math.random()>0.5 ? '#fff2c4' : '#ff7a2e';
    const x = rand(0,c.width), y = rand(0,c.height), r = rand(6,40);
    ctx.beginPath(); ctx.ellipse(x,y,r,r*0.5,rand(0,Math.PI),0,Math.PI*2); ctx.fill();
  }
  ctx.globalAlpha = 1;
  return toTexture(c);
}

/* Small radial-glow sprite used for stars / flares / particles */
function spriteTexture(hex='#ffffff', hard=false){
  const c = document.createElement('canvas'); c.width=64; c.height=64;
  const ctx = c.getContext('2d');
  const grad = ctx.createRadialGradient(32,32,0,32,32,32);
  grad.addColorStop(0, hex);
  grad.addColorStop(hard?0.25:0.18, hex);
  grad.addColorStop(1,'rgba(0,0,0,0)');
  ctx.fillStyle = grad; ctx.fillRect(0,0,64,64);
  const tex = new THREE.CanvasTexture(c);
  tex.needsUpdate = true;
  return tex;
}

const glowSprite = spriteTexture('#ffffff');

/* ---------------------------------------------------------------
   5. STARFIELD (twinkling, shader-based)
   --------------------------------------------------------------- */
function buildStarfield(){
  const N = QUALITY.starCount;
  const positions = new Float32Array(N*3);
  const colors = new Float32Array(N*3);
  const sizes = new Float32Array(N);
  const phases = new Float32Array(N);
  const speeds = new Float32Array(N);

  const palette = [ new THREE.Color('#ffffff'), new THREE.Color('#cfe0ff'), new THREE.Color('#fff3d6'), new THREE.Color('#ffd6c9') ];

  for (let i=0;i<N;i++){
    const r = rand(280, 2400);
    const theta = Math.acos(rand(-1,1));
    const phi = rand(0, Math.PI*2);
    positions[i*3]   = r*Math.sin(theta)*Math.cos(phi);
    positions[i*3+1] = r*Math.cos(theta);
    positions[i*3+2] = r*Math.sin(theta)*Math.sin(phi);
    const col = pick(palette);
    colors[i*3]=col.r; colors[i*3+1]=col.g; colors[i*3+2]=col.b;
    sizes[i] = rand(0.6, 2.4);
    phases[i] = rand(0, Math.PI*2);
    speeds[i] = rand(0.4, 2.2);
  }

  const geo = new THREE.BufferGeometry();
  geo.setAttribute('position', new THREE.BufferAttribute(positions,3));
  geo.setAttribute('aColor', new THREE.BufferAttribute(colors,3));
  geo.setAttribute('aSize', new THREE.BufferAttribute(sizes,1));
  geo.setAttribute('aPhase', new THREE.BufferAttribute(phases,1));
  geo.setAttribute('aSpeed', new THREE.BufferAttribute(speeds,1));

  const mat = new THREE.ShaderMaterial({
    uniforms: { uTime: { value: 0 } },
    vertexShader: `
      attribute float aSize;
      attribute float aPhase;
      attribute float aSpeed;
      attribute vec3 aColor;
      varying vec3 vColor;
      varying float vTwinkle;
      uniform float uTime;
      void main(){
        vColor = aColor;
        vTwinkle = 0.55 + 0.45 * sin(uTime * aSpeed + aPhase);
        vec4 mvPosition = modelViewMatrix * vec4(position, 1.0);
        gl_PointSize = aSize * (340.0 / -mvPosition.z) * vTwinkle;
        gl_Position = projectionMatrix * mvPosition;
      }
    `,
    fragmentShader: `
      varying vec3 vColor;
      varying float vTwinkle;
      void main(){
        float d = length(gl_PointCoord - vec2(0.5));
        float alpha = smoothstep(0.5, 0.0, d);
        gl_FragColor = vec4(vColor * vTwinkle, alpha);
      }
    `,
    transparent: true,
    depthWrite: false,
    blending: THREE.AdditiveBlending,
  });

  const points = new THREE.Points(geo, mat);
  scene.add(points);
  return mat;
}

/* Nebula / Milky-Way backdrop sphere */
function buildNebula(){
  const size = 2048;
  const c = document.createElement('canvas'); c.width = size; c.height = size/2;
  const ctx = c.getContext('2d');
  ctx.fillStyle = '#01020a'; ctx.fillRect(0,0,c.width,c.height);

  const blobColors = ['rgba(120,70,190,0.20)','rgba(50,90,190,0.18)','rgba(190,70,140,0.14)','rgba(70,150,190,0.12)'];
  for (let i=0;i<26;i++){
    const x = rand(0,c.width), y = rand(0,c.height), r = rand(120,420);
    const grad = ctx.createRadialGradient(x,y,0,x,y,r);
    grad.addColorStop(0, pick(blobColors));
    grad.addColorStop(1,'rgba(0,0,0,0)');
    ctx.fillStyle = grad;
    ctx.beginPath(); ctx.arc(x,y,r,0,Math.PI*2); ctx.fill();
  }
  // milky-way band
  ctx.save();
  ctx.translate(c.width/2, c.height/2);
  ctx.rotate(-0.35);
  const bandGrad = ctx.createLinearGradient(0,-140,0,140);
  bandGrad.addColorStop(0,'rgba(255,255,255,0)');
  bandGrad.addColorStop(0.5,'rgba(210,215,240,0.16)');
  bandGrad.addColorStop(1,'rgba(255,255,255,0)');
  ctx.fillStyle = bandGrad;
  ctx.fillRect(-c.width, -140, c.width*2, 280);
  ctx.restore();
  // fine dust speckle
  for (let i=0;i<4000;i++){
    ctx.globalAlpha = rand(0.03,0.16);
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(rand(0,c.width), rand(0,c.height), 1, 1);
  }
  ctx.globalAlpha = 1;

  const tex = new THREE.CanvasTexture(c);
  tex.colorSpace = THREE.SRGBColorSpace;
  const geo = new THREE.SphereGeometry(2800, 32, 24);
  const mat = new THREE.MeshBasicMaterial({ map: tex, side: THREE.BackSide, fog:false, depthWrite:false });
  const mesh = new THREE.Mesh(geo, mat);
  scene.add(mesh);
}

/* ---------------------------------------------------------------
   6. SUN
   --------------------------------------------------------------- */
const sunGroup = new THREE.Group();
scene.add(sunGroup);

const sunMat = new THREE.MeshBasicMaterial({ map: textureSun() });
const sunMesh = new THREE.Mesh(new THREE.SphereGeometry(SUN.radius, 48, 48), sunMat);
sunGroup.add(sunMesh);

// soft corona sprite
const corona = new THREE.Sprite(new THREE.SpriteMaterial({ map: spriteTexture('#ffb86b'), color:0xffb86b, transparent:true, opacity:0.55, blending:THREE.AdditiveBlending, depthWrite:false }));
corona.scale.set(SUN.radius*6, SUN.radius*6, 1);
sunGroup.add(corona);

const sunLight = new THREE.PointLight(0xfff2d6, 3.4, 0, 0);
sunLight.decay = 0.6;
if (QUALITY.shadows){
  sunLight.castShadow = true;
  sunLight.shadow.mapSize.set(1024,1024);
  sunLight.shadow.camera.near = 1;
  sunLight.shadow.camera.far = 400;
}
sunGroup.add(sunLight);
scene.add(new THREE.AmbientLight(0x223344, 0.35));

// Lens flare
const flareTexBig = spriteTexture('#ffe3b0', true);
const flareTexRing = spriteTexture('#7fd9ff', true);
const lensflare = new Lensflare();
lensflare.addElement(new LensflareElement(flareTexBig, 260, 0, sunLight.color));
lensflare.addElement(new LensflareElement(flareTexRing, 40, 0.35));
lensflare.addElement(new LensflareElement(flareTexRing, 70, 0.6));
lensflare.addElement(new LensflareElement(flareTexRing, 110, 0.9));
sunLight.add(lensflare);

// Sun-hugging particles
function buildSunParticles(){
  const N = 500;
  const positions = new Float32Array(N*3);
  for (let i=0;i<N;i++){
    const r = SUN.radius * rand(1.02,1.35);
    const theta = Math.acos(rand(-1,1));
    const phi = rand(0,Math.PI*2);
    positions[i*3] = r*Math.sin(theta)*Math.cos(phi);
    positions[i*3+1] = r*Math.cos(theta);
    positions[i*3+2] = r*Math.sin(theta)*Math.sin(phi);
  }
  const geo = new THREE.BufferGeometry();
  geo.setAttribute('position', new THREE.BufferAttribute(positions,3));
  const mat = new THREE.PointsMaterial({ size:0.55, map:glowSprite, color:0xffcf8a, transparent:true, blending:THREE.AdditiveBlending, depthWrite:false, sizeAttenuation:true });
  const pts = new THREE.Points(geo, mat);
  sunGroup.add(pts);
  return pts;
}
const sunParticles = buildSunParticles();

/* ---------------------------------------------------------------
   7. PLANET FACTORY
   --------------------------------------------------------------- */
const planetMeshes = [];   // { cfg, group(orbit-anchor), mesh, cloudMesh, orbitLine, angle, label }
const clickables = [];     // meshes registered for raycasting
const labelLayer = document.getElementById('label-layer');
const navEl = document.getElementById('planet-nav');

function makePlanetTexture(cfg){
  switch(cfg.texture){
    case 'rocky': return textureRocky(cfg.palette);
    case 'mars': return textureRocky(cfg.palette);
    case 'venus': return textureVenus(cfg.palette);
    case 'earth': return textureEarth(cfg.palette);
    case 'jupiter': return textureBanded(cfg.palette, { storm:true, turbulence:1.3 });
    case 'saturn': return textureBanded(cfg.palette, { storm:false, turbulence:0.7 });
    case 'uranus': return textureBanded(cfg.palette, { storm:false, turbulence:0.3 });
    case 'neptune': return textureBanded(cfg.palette, { storm:false, turbulence:0.9 });
    default: return textureRocky(cfg.palette);
  }
}

function createOrbitLine(radius){
  const segments = 128;
  const pts = [];
  for (let i=0;i<=segments;i++){
    const a = (i/segments)*Math.PI*2;
    pts.push(new THREE.Vector3(Math.cos(a)*radius, 0, Math.sin(a)*radius));
  }
  const geo = new THREE.BufferGeometry().setFromPoints(pts);
  const mat = new THREE.LineBasicMaterial({ color:0x5eead4, transparent:true, opacity:0.22 });
  const line = new THREE.LineLoop(geo, mat);
  return line;
}

function createLabel(text, key){
  const div = document.createElement('div');
  div.className = 'planet-label';
  div.innerHTML = `<span class="dot"></span>${text}`;
  div.addEventListener('click', () => selectPlanet(key));
  labelLayer.appendChild(div);
  return div;
}

function createNavButton(cfg){
  const btn = document.createElement('button');
  btn.textContent = cfg.name.toUpperCase();
  btn.dataset.key = cfg.key;
  btn.addEventListener('click', () => selectPlanet(cfg.key));
  navEl.appendChild(btn);
  return btn;
}

PLANETS.forEach(cfg => {
  const orbitAnchor = new THREE.Group();
  scene.add(orbitAnchor);

  const orbitLine = createOrbitLine(cfg.distance);
  scene.add(orbitLine);

  const tex = makePlanetTexture(cfg);
  const mat = new THREE.MeshStandardMaterial({ map: tex, roughness: 0.85, metalness: 0.05 });
  const mesh = new THREE.Mesh(new THREE.SphereGeometry(cfg.radius, IS_MOBILE?24:40, IS_MOBILE?24:40), mat);
  mesh.position.set(cfg.distance, 0, 0);
  mesh.rotation.z = cfg.tilt;
  mesh.castShadow = QUALITY.shadows;
  mesh.receiveShadow = QUALITY.shadows;
  mesh.userData.key = cfg.key;
  orbitAnchor.add(mesh);
  clickables.push(mesh);

  let cloudMesh = null;
  if (cfg.texture === 'earth'){
    const cloudMat = new THREE.MeshStandardMaterial({ map: textureClouds(), transparent:true, opacity:0.55, depthWrite:false, roughness:1 });
    cloudMesh = new THREE.Mesh(new THREE.SphereGeometry(cfg.radius*1.015, 32, 32), cloudMat);
    mesh.add(cloudMesh);
  }

  let ringMesh = null;
  if (cfg.hasRings){
    const ringGeo = new THREE.RingGeometry(cfg.radius*1.5, cfg.radius*2.6, 96, 1);
    // remap UV so texture maps radially, not per-triangle
    const uv = ringGeo.attributes.uv;
    const pos = ringGeo.attributes.position;
    const v3 = new THREE.Vector3();
    for (let i=0;i<pos.count;i++){
      v3.fromBufferAttribute(pos,i);
      const t = (v3.length() - cfg.radius*1.5) / (cfg.radius*1.1);
      uv.setXY(i, t, 0.5);
    }
    const ringMat = new THREE.MeshStandardMaterial({ map: textureRing('#d8c79c'), side: THREE.DoubleSide, transparent:true, roughness:1 });
    ringMesh = new THREE.Mesh(ringGeo, ringMat);
    ringMesh.rotation.x = Math.PI/2 - 0.38;
    ringMesh.receiveShadow = QUALITY.shadows;
    mesh.add(ringMesh);
  }

  // moons
  const moonEntries = [];
  if (cfg.moons){
    cfg.moons.forEach(m => {
      const mAnchor = new THREE.Group();
      mesh.add(mAnchor);
      const mMesh = new THREE.Mesh(
        new THREE.SphereGeometry(m.radius, 20, 20),
        new THREE.MeshStandardMaterial({ map: textureRocky(m.palette), roughness:0.9 })
      );
      mMesh.position.set(m.distance,0,0);
      mMesh.castShadow = QUALITY.shadows;
      mMesh.receiveShadow = QUALITY.shadows;
      mAnchor.add(mMesh);
      moonEntries.push({ cfg:m, anchor:mAnchor, mesh:mMesh, angle:rand(0,Math.PI*2) });
    });
  }

  const label = createLabel(cfg.name, cfg.key);
  createNavButton(cfg);

  const orbitAngularSpeed = (Math.PI*2) / (YEAR_SECONDS * (cfg.orbitPeriodDays/365.25));
  const rotationAngularSpeed = cfg.rotationDir * (Math.PI*2) / (YEAR_SECONDS * (cfg.rotationPeriodDays/365.25)) * 0.02;

  planetMeshes.push({
    cfg, orbitAnchor, mesh, cloudMesh, ringMesh, orbitLine, label,
    angle: rand(0, Math.PI*2),
    orbitSpeed: orbitAngularSpeed,
    rotSpeed: rotationAngularSpeed,
    moons: moonEntries,
  });
});

/* ---------------------------------------------------------------
   8. ASTEROID BELT
   --------------------------------------------------------------- */
const beltGroup = new THREE.Group();
scene.add(beltGroup);
{
  const geo = new THREE.IcosahedronGeometry(0.14, 0);
  const mat = new THREE.MeshStandardMaterial({ color:0x8a8378, roughness:1, metalness:0.05 });
  const inst = new THREE.InstancedMesh(geo, mat, QUALITY.asteroidCount);
  const dummy = new THREE.Object3D();
  for (let i=0;i<QUALITY.asteroidCount;i++){
    const r = rand(BELT_INNER, BELT_OUTER);
    const a = rand(0, Math.PI*2);
    const y = rand(-1.4,1.4);
    dummy.position.set(Math.cos(a)*r, y, Math.sin(a)*r);
    dummy.rotation.set(rand(0,Math.PI), rand(0,Math.PI), rand(0,Math.PI));
    const s = rand(0.4, 1.6);
    dummy.scale.setScalar(s);
    dummy.updateMatrix();
    inst.setMatrixAt(i, dummy.matrix);
  }
  inst.castShadow = false; inst.receiveShadow = false;
  beltGroup.add(inst);
}

/* ---------------------------------------------------------------
   9. COMETS
   --------------------------------------------------------------- */
const comets = [];
function buildComet(seed){
  const group = new THREE.Group();
  const head = new THREE.Mesh(
    new THREE.SphereGeometry(0.35, 12, 12),
    new THREE.MeshBasicMaterial({ color:0xbfe9ff })
  );
  group.add(head);
  const glow = new THREE.Sprite(new THREE.SpriteMaterial({ map: glowSprite, color:0x9fdcff, transparent:true, opacity:0.85, blending:THREE.AdditiveBlending, depthWrite:false }));
  glow.scale.set(2.4,2.4,1);
  head.add(glow);

  const TRAIL_LEN = 46;
  const trailPositions = new Float32Array(TRAIL_LEN*3);
  const trailColors = new Float32Array(TRAIL_LEN*3);
  const history = [];
  const geo = new THREE.BufferGeometry();
  geo.setAttribute('position', new THREE.BufferAttribute(trailPositions,3));
  geo.setAttribute('color', new THREE.BufferAttribute(trailColors,3));
  const mat = new THREE.PointsMaterial({ size:0.5, map:glowSprite, vertexColors:true, transparent:true, blending:THREE.AdditiveBlending, depthWrite:false, sizeAttenuation:true });
  const trail = new THREE.Points(geo, mat);
  scene.add(trail);
  scene.add(group);

  comets.push({
    group, head, trail, history, TRAIL_LEN,
    a: rand(60,150), e: rand(0.75,0.92), incl: rand(-0.5,0.5), phase: seed*2.1, speed: rand(0.15,0.3)
  });
}
buildComet(1); buildComet(2); buildComet(3);

/* ---------------------------------------------------------------
   10. BUILD BACKGROUND
   --------------------------------------------------------------- */
let starMat;

/* ---------------------------------------------------------------
   11. CAMERA FLIGHT / SELECTION
   --------------------------------------------------------------- */
const raycaster = new THREE.Raycaster();
const pointerNDC = new THREE.Vector2();
let pointerDownPos = null;

function worldPosOf(entry){
  const p = new THREE.Vector3();
  entry.mesh.getWorldPosition(p);
  return p;
}

function flyTo(targetPos, lookAt, duration=1.4){
  state.flight = {
    t: 0, duration,
    startPos: camera.position.clone(),
    endPos: targetPos.clone(),
    startTarget: controls.target.clone(),
    endTarget: lookAt.clone(),
  };
  controls.enabled = false;
}

function easeInOutCubic(t){ return t<0.5 ? 4*t*t*t : 1-Math.pow(-2*t+2,3)/2; }

function selectPlanet(key){
  if (key === 'sun'){
    state.selected = 'sun';
    updateNavActive('sun');
    const dir = new THREE.Vector3(0.6,0.35,1).normalize();
    flyTo(dir.multiplyScalar(SUN.radius*4.2), new THREE.Vector3(0,0,0));
    showInfo({ name:'Sun', type:'G-TYPE MAIN-SEQUENCE STAR',
      desc:'The star at the heart of our solar system, containing 99.8% of its total mass.',
      facts:{ diameter:'1,391,000 km', distance:'0 km (center)', moons:'—', day:'~27 Earth days', year:'—', temp:'5,500°C surface' },
      notes:['The Sun fuses roughly 600 million tons of hydrogen into helium every second.',
             'Light from the Sun takes about 8 minutes and 20 seconds to reach Earth.',
             'It accounts for about 99.86% of the total mass of the solar system.'] });
    return;
  }
  const entry = planetMeshes.find(p => p.cfg.key === key);
  if (!entry) return;
  state.selected = key;
  const p = worldPosOf(entry);
  const dist = entry.cfg.radius * 5.5 + 3.5;
  const dir = camera.position.clone().sub(p);
  if (dir.lengthSq() < 0.001) dir.set(1,0.4,1);
  dir.normalize().multiplyScalar(dist);
  dir.y = Math.max(dir.y, dist*0.28);
  flyTo(p.clone().add(dir), p);
  showInfo(entry.cfg);
  updateNavActive(key);
}

function updateNavActive(key){
  [...navEl.children].forEach(btn => btn.classList.toggle('active', btn.dataset.key === key));
}

function resetCamera(){
  state.selected = null;
  flyTo(DEFAULT_CAM_POS, DEFAULT_TARGET, 1.2);
  closeInfo();
  updateNavActive(null);
}

/* ---------------------------------------------------------------
   12. INFO PANEL
   --------------------------------------------------------------- */
const infoPanel = document.getElementById('info-panel');
function showInfo(cfg){
  document.getElementById('info-type').textContent = cfg.type || '';
  document.getElementById('info-name').textContent = cfg.name;
  document.getElementById('info-desc').textContent = cfg.desc || '';
  const f = cfg.facts || {};
  document.getElementById('stat-diameter').textContent = f.diameter || '—';
  document.getElementById('stat-distance').textContent = f.distance || '—';
  document.getElementById('stat-moons').textContent = f.moons || '—';
  document.getElementById('stat-day').textContent = f.day || '—';
  document.getElementById('stat-year').textContent = f.year || '—';
  document.getElementById('stat-temp').textContent = f.temp || '—';
  const list = document.getElementById('info-facts-list');
  list.innerHTML = '';
  (cfg.notes||[]).forEach(n => {
    const li = document.createElement('li');
    li.textContent = n;
    list.appendChild(li);
  });
  infoPanel.classList.add('open');
}
function closeInfo(){ infoPanel.classList.remove('open'); }
document.getElementById('info-close').addEventListener('click', () => { closeInfo(); resetCamera(); });

/* ---------------------------------------------------------------
   13. POINTER / CLICK HANDLING
   --------------------------------------------------------------- */
renderer.domElement.addEventListener('pointerdown', (e) => { pointerDownPos = { x:e.clientX, y:e.clientY }; });
renderer.domElement.addEventListener('pointerup', (e) => {
  if (!pointerDownPos) return;
  const dx = e.clientX - pointerDownPos.x, dy = e.clientY - pointerDownPos.y;
  if (Math.sqrt(dx*dx+dy*dy) > 6) return; // was a drag, not a click
  pointerNDC.x = (e.clientX / window.innerWidth) * 2 - 1;
  pointerNDC.y = -(e.clientY / window.innerHeight) * 2 + 1;
  raycaster.setFromCamera(pointerNDC, camera);
  const hits = raycaster.intersectObjects([...clickables, sunMesh], false);
  if (hits.length){
    const obj = hits[0].object;
    if (obj === sunMesh) selectPlanet('sun');
    else selectPlanet(obj.userData.key);
  }
});

/* ---------------------------------------------------------------
   14. UI WIRING
   --------------------------------------------------------------- */
const btnPlay = document.getElementById('btn-play');
const iconPlay = document.getElementById('icon-play');
const iconPause = document.getElementById('icon-pause');
btnPlay.addEventListener('click', () => {
  state.playing = !state.playing;
  iconPlay.style.display = state.playing ? 'none' : 'block';
  iconPause.style.display = state.playing ? 'block' : 'none';
});

const speedSlider = document.getElementById('speed-slider');
const speedValue = document.getElementById('speed-value');
speedSlider.addEventListener('input', () => {
  state.speed = parseFloat(speedSlider.value);
  speedValue.textContent = state.speed.toFixed(2) + '×';
});

document.getElementById('toggle-orbits').addEventListener('change', (e) => {
  state.showOrbits = e.target.checked;
  planetMeshes.forEach(p => p.orbitLine.visible = state.showOrbits);
});
document.getElementById('toggle-labels').addEventListener('change', (e) => {
  state.showLabels = e.target.checked;
});
document.getElementById('btn-reset').addEventListener('click', resetCamera);

document.getElementById('btn-darkmode').addEventListener('click', () => {
  document.body.classList.toggle('mode-light');
});
document.getElementById('btn-fullscreen').addEventListener('click', () => {
  if (!document.fullscreenElement) document.documentElement.requestFullscreen?.();
  else document.exitFullscreen?.();
});

// "Sun" entry in nav
(function addSunNav(){
  const btn = document.createElement('button');
  btn.textContent = 'SUN';
  btn.dataset.key = 'sun';
  btn.addEventListener('click', () => selectPlanet('sun'));
  navEl.insertBefore(btn, navEl.firstChild);
})();

/* ---------------------------------------------------------------
   15. RESIZE
   --------------------------------------------------------------- */
window.addEventListener('resize', () => {
  camera.aspect = window.innerWidth/window.innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(window.innerWidth, window.innerHeight);
  composer.setSize(window.innerWidth, window.innerHeight);
  if (bloomPass) bloomPass.setSize(window.innerWidth, window.innerHeight);
});

/* ---------------------------------------------------------------
   16. MAIN LOOP
   --------------------------------------------------------------- */
const clock = new THREE.Clock();
const _v1 = new THREE.Vector3(), _v2 = new THREE.Vector3();

function updateLabels(){
  const camDir = new THREE.Vector3();
  camera.getWorldDirection(camDir);
  planetMeshes.forEach(entry => {
    const worldPos = worldPosOf(entry);
    _v1.copy(worldPos).project(camera);
    const behind = _v1.z > 1;
    const visible = state.showLabels && !behind && _v1.x > -1.1 && _v1.x < 1.1 && _v1.y > -1.1 && _v1.y < 1.1;
    entry.label.classList.toggle('is-hidden', !visible);
    if (visible){
      const x = (_v1.x*0.5+0.5) * window.innerWidth;
      const y = (-_v1.y*0.5+0.5) * window.innerHeight;
      entry.label.style.left = x + 'px';
      entry.label.style.top = y + 'px';
    }
  });
}

function updateComets(dt, elapsed){
  comets.forEach(c => {
    const a = c.phase + elapsed*c.speed;
    const r = c.a * (1 - c.e*c.e) / (1 + c.e*Math.cos(a));
    const x = Math.cos(a)*r;
    const z = Math.sin(a)*r;
    const y = Math.sin(a*0.7)*r*Math.sin(c.incl)*0.3;
    c.group.position.set(x,y,z);

    c.history.unshift(c.group.position.clone());
    if (c.history.length > c.TRAIL_LEN) c.history.pop();
    const posAttr = c.trail.geometry.attributes.position;
    const colAttr = c.trail.geometry.attributes.color;
    for (let i=0;i<c.TRAIL_LEN;i++){
      const p = c.history[i] || c.history[c.history.length-1] || c.group.position;
      posAttr.setXYZ(i, p.x, p.y, p.z);
      const fade = 1 - i/c.TRAIL_LEN;
      colAttr.setXYZ(i, 0.55*fade+0.1, 0.8*fade+0.1, 1.0*fade+0.2);
    }
    posAttr.needsUpdate = true; colAttr.needsUpdate = true;
  });
}

function updateFlight(dt){
  const f = state.flight;
  if (!f) return;
  f.t += dt / f.duration;
  const t = Math.min(f.t, 1);
  const e = easeInOutCubic(t);
  camera.position.lerpVectors(f.startPos, f.endPos, e);
  controls.target.lerpVectors(f.startTarget, f.endTarget, e);
  if (t >= 1){
    state.flight = null;
    controls.enabled = true;
  }
}

function tick(){
  const dt = Math.min(clock.getDelta(), 0.05);
  const elapsed = clock.elapsedTime;

  if (starMat) starMat.uniforms.uTime.value = elapsed;
  sunMesh.rotation.y += dt*0.02;
  corona.material.rotation += dt*0.01;
  sunParticles.rotation.y += dt*0.015;

  if (state.playing){
    const dSim = dt * state.speed;
    state.simDays += dSim * (365.25/YEAR_SECONDS);

    planetMeshes.forEach(entry => {
      entry.angle += entry.orbitSpeed * dSim;
      entry.orbitAnchor.rotation.y = entry.angle;
      entry.mesh.rotation.y += entry.rotSpeed * dSim * 40;
      if (entry.cloudMesh) entry.cloudMesh.rotation.y += dt*0.01*state.speed;
      entry.moons.forEach(m => {
        m.angle += (Math.PI*2/(YEAR_SECONDS*(m.cfg.orbitPeriodDays/365.25))) * dSim;
        m.anchor.rotation.y = m.angle;
      });
    });
    beltGroup.rotation.y += dt*0.006*state.speed;
    updateComets(dSim, elapsed);
  }

  updateFlight(dt);
  controls.update();
  updateLabels();

  const simDate = document.getElementById('sim-date');
  const y = Math.floor(state.simDays/365.25);
  const d = Math.floor(state.simDays%365.25);
  simDate.textContent = `Y${y} · D${d}`;

  composer.render();
  requestAnimationFrame(tick);
}

/* ---------------------------------------------------------------
   17. BOOT SEQUENCE
   --------------------------------------------------------------- */
(async function boot(){
  setLoad(15, 'Painting planetary surfaces…');
  await nextFrame();
  setLoad(40, 'Scattering stars across the void…');
  await nextFrame();
  starMat = buildStarfield();
  setLoad(65, 'Rendering the Milky Way…');
  await nextFrame();
  buildNebula();
  setLoad(85, 'Aligning orbital mechanics…');
  await nextFrame();
  setLoad(100, 'Ignition.');
  await nextFrame();
  loaderEl.classList.add('hidden');
  tick();
})();
